#ifndef INCLUDE_MODEL_GAMEOBJECT_CHARGERTYPE_HPP_
#define INCLUDE_MODEL_GAMEOBJECT_CHARGERTYPE_HPP_

enum class ChargerType { NORMAL, RANDOM, RANDOM_SAFE };

#endif // !INCLUDE_MODEL_GAMEOBJECT_CHARGERTYPE_HPP_
